### ISSUE TITLE
Clientcrash when breaking Enddoor

### ISSUE THREAD

**Issue by Kernmann** [GeheimagentNr1/ManyIdeasDoors#1]
**Versions**
Minecraft Version: 1.17.1
Minecraft Forge Version: 37.1.0
Mod Version: 1.2.0

**Log files**
[latest.log](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/7697791/latest.log)

**Describe the bug**
Client crash after removing placed Enddoor

**To Reproduce**
1. place Enddoor
2. break/remove Enddoor
3. Minecraft client crash

**Expected behaviour**
Client shouldn't crash

**Additional context**
Tested on Multiplayer with Forge Server 37.1.0 & Mod version 1.2.0 installed, all connected clients crashed

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Investigations running</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>1.0.1 (1.14.4, 1.15.2), 1.1.1 (1.16.5), 1.2.1 (1.17.1)</td></tr><tr><th>Fix release date:</th><td>12.12.2021</td></tr></tbody></table>

**Issue confirmed for:**

*   The bug was seam in the 1.18, it seems that other versions have the issue too.

**TODOs:**

*   [x] Implement fix for Minecraft version 1.14.4, 1.15.2, 1.16.5, 1.17.1
